wandb_version: 1

BATCH_SIZE:
  desc: null
  value: 256
BUDGET_RANGE:
  desc: null
  value:
  - 2.999
  - 3
GAUSSIAN_NUM:
  desc: null
  value:
  - 8
  - 12
GREEDY:
  desc: null
  value: false
NUM_Runner:
  desc: null
  value: 10
NUM_Worker:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1664549522.910613
    t:
      1:
      - 1
      - 5
      - 30
      - 53
      - 55
      2:
      - 1
      - 5
      - 30
      - 53
      - 55
      3:
      - 19
      - 23
      - 24
      4: 3.10.4
      5: 0.13.3
      8:
      - 5
